# Generated by Django 5.1.7 on 2025-04-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_authh_status_user_auth_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfirmation',
            old_name='is_confirm',
            new_name='is_confirmed',
        ),
    ]
